# Generated by Django 2.2.5 on 2020-02-21 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.TextField(max_length=50, verbose_name='1つ目')),
                ('line_two', models.TextField(max_length=50, verbose_name='2つ目')),
                ('line_three', models.TextField(max_length=50, verbose_name='3つ目')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
