# Generated by Django 2.2.5 on 2020-03-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThreeLineDiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='line_one',
            field=models.CharField(max_length=100, verbose_name='1つ目'),
        ),
        migrations.AlterField(
            model_name='post',
            name='line_three',
            field=models.CharField(max_length=100, verbose_name='3つ目'),
        ),
        migrations.AlterField(
            model_name='post',
            name='line_two',
            field=models.CharField(max_length=100, verbose_name='2つ目'),
        ),
    ]
